
from django.db import migrations, models
import django.db.models.deletion
# Generated by Django 4.1.5 on 2023-01-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('cat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubCat',
            fields=[
                ('subcat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('subcat_name', models.CharField(max_length=50)),
                ('cat_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='Products.cat')),
            ],
        ),
        migrations.CreateModel(
            name='P_Details',
            fields=[
                ('p_id', models.IntegerField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=50)),
                ('p_price', models.IntegerField()),
                ('p_qty', models.IntegerField()),
                ('p_type', models.CharField(max_length=30)),
                ('p_fabric', models.CharField(max_length=30)),
                ('p_size', models.CharField(max_length=30)),
                ('p_img', models.CharField(max_length=50)),
                ('p_desc', models.CharField(max_length=100)),
                ('p_color', models.CharField(max_length=50)),
                ('subcat_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='Products.subcat')),
            ],),
            migrations.CreateModel(
            name='p_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=30)),
                ('p_type', models.CharField(max_length=20)),
                ('p_fabric', models.CharField(max_length=20)),
                ('p_size', models.CharField(max_length=3)),
                ('p_custm', models.CharField(max_length=10)),
                ('p_image', models.CharField(max_length=100)),
                ('p_des', models.CharField(max_length=100)),
            ],),
    ]
    
