# Generated by Django 4.1.5 on 2023-01-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='p_details1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcat_id', models.IntegerField()),
                ('p_name', models.CharField(max_length=30)),
                ('p_price', models.IntegerField()),
                ('p_qty', models.IntegerField()),
                ('p_type', models.CharField(max_length=20)),
                ('p_fabric', models.CharField(max_length=20)),
                ('p_size', models.CharField(max_length=3)),
                ('p_custm', models.CharField(max_length=10)),
                ('p_image', models.CharField(max_length=100)),
                ('p_des', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='p_details',
        ),
    ]
