# Generated by Django 4.1.5 on 2023-01-17 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_p_details1_delete_p_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='cat',
            fields=[
                ('cat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='p_details1',
            name='id',
        ),
        migrations.AddField(
            model_name='p_details1',
            name='p_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='subcat',
            fields=[
                ('subcat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('subcat_name', models.CharField(max_length=20)),
                ('cat_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Products.cat')),
            ],
        ),
        migrations.AlterField(
            model_name='p_details1',
            name='subcat_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Products.subcat'),
        ),
    ]
