# Generated by Django 4.1.5 on 2023-01-17 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_alter_user_phone_no_alter_user_zipcode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='user_registration',
        ),
    ]
