# Generated by Django 4.1.5 on 2023-01-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0006_rename_user_user_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='password',
            field=models.CharField(default=0, max_length=18),
        ),
    ]
