# Generated by Django 4.1.5 on 2023-01-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0007_user_registration_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_registration',
            name='phone_no',
            field=models.CharField(max_length=11),
        ),
    ]
